import numpy as np
arr= np.array([1,2,3,4,5])
print(arr)
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)
arr3=np.zeros((3,3))
print(arr3)
print("\n")
print(np.ones((2,2)))
print("\n")
print(np.full((2,3),9))
print("\n")
print(np.eye(3))