import os
import pathlib
from pathlib import Path 

q={'math':'jan 6', 'chem':'7'}
print(q['math'])
print(q.get('math'))
print(q.keys())
q['caed']='march'
print(q.keys())
b, sep, a='f2 my name is pranav kaushik'.partition(' ')
print(a)
print(ord('A'))
print(chr(65))
m= '      my name is pranav     '
print(m.split(' '))
print('_'.join(m))
print('_'.join(m.split(' ')))
print('\'', m.lstrip(), '\'')
print('\'', m.rstrip(), '\'')
print('\'', m.strip(), '\'')
print(m.replace('m','s'))
print(m.upper())
print(m.lower())
print(m.partition('na'))
print(m.rjust(40,'='))
print(m.ljust(40,'='))
print(m.center(40,'='))
print('hello world')
a,b,c=m.partition('n')
print(a,b,c)
print(Path.cwd())
print(Path.home())
print(os.path.relpath('.'))
print(Path.cwd().parent)
print(os.listdir())
p=Path('/Users/gpranavkaushik')
print(p.exists())
s=open('try.txt','r')
w=s.read()
print(w)
t2=([22,3,4,5])
print(t2)
x=int(input('enter a no.'))
assert x>0, 'the no.should be positive '
print('no. is positive')